export const recentData = [
	{
		title: 'Красноярск',
		img: '../public/manWithBox.png',
		imgTitle: '50 тонн текстиля в Красноярск',
		typeImg: '../public/miniAirplane.svg',
		typeDelivery: 'АВИА',
		day: 15,
		text: 'Включено: таможенное оформление, полное страхование, сертификация',
		price: '$ 22 000',
		id: 1,
	},
	{
		title: 'Челябинск',
		img: '../public/folding.png',
		imgTitle: '12 тонн жвачки в Челябинск',
		typeImg: '../public/miniCar.svg',
		typeDelivery: 'АВТО',
		day: 32,
		text: 'Включено: таможенное оформление',
		price: '$ 3 000',
		id: 2,
	},
	{
		title: 'Красноярск',
		img: '../public/manWithBox.png',
		imgTitle: '50 тонн текстиля в Красноярск',
		typeImg: '../public/miniAirplane.svg',
		typeDelivery: 'АВИА',
		day: 15,
		text: 'Включено: таможенное оформление, полное страхование, сертификация',
		price: '$ 22 000',
		id: 3,
	},
	{
		title: 'Челябинск',
		img: '../public/folding.png',
		imgTitle: '12 тонн жвачки в Челябинск',
		typeImg: '../public/miniCar.svg',
		typeDelivery: 'АВТО',
		day: 32,
		text: 'Включено: таможенное оформление',
		price: '$ 3 000',
		id: 4,
	},
	{
		title: 'Челябинск',
		img: '../public/folding.png',
		imgTitle: '12 тонн жвачки в Челябинск',
		typeImg: '../public/miniCar.svg',
		typeDelivery: 'АВТО',
		day: 32,
		text: 'Включено: таможенное оформление',
		price: '$ 3 000',
		id: 4,
	},
]